'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('games', [
      // ========================  Jornada 1  =============================
            {
              season: "2020-2021",
              tournament: "clausura",  
              journey: 1, 
              date: "08/01",
              time: "19:30 hr", 
              localId: 8, 
              localGol: 1, 
              visitorId: 13, 
              visitorGol: 1, 
              stadium: "Cuauhtémoc",
              result: "Empate",
              createdAt: new Date(), 
              updatedAt: new Date()
          },
          {
              season: "2020-2021",
              tournament: "clausura",
              journey: 1, 
              date: "08/01",
              time: "21:06 hr", 
              localId: 1, 
              localGol: 0, 
              visitorId: 12, 
              visitorGol: 0, 
              stadium: "Caliente",
              result: "Empate",
              createdAt: new Date(), 
              updatedAt: new Date()
          },
          {//3er partido
              season: "2020-2021",
              tournament: "clausura",
              journey: 1, 
              date: "08/01",
              time: "21:30 hr", 
              localId: 11, 
              localGol: 3, 
              visitorId: 15, 
              visitorGol: 2, 
              stadium: "Estadio Mazatlán",
              result: "Empate",
              createdAt: new Date(), 
              updatedAt: new Date()
          },
          {
              season: "2020-2021",
              tournament: "clausura",
              journey: 1, 
              date: "09/01",
              time: "17:00 hr", 
              localId: 18, 
              localGol: 0, 
              visitorId: 3, 
              visitorGol: 2, 
              stadium: "Jalisco",
              result: "Empate",
              createdAt: new Date(), 
              updatedAt: new Date()
          },
          {//5to partido
              season: "2020-2021",
              tournament: "clausura",
              journey: 1, 
              date: "09/01",
              time: "19:00 hr", 
              localId: 9, 
              localGol: 2, 
              visitorId: 16, 
              visitorGol: 0, 
              stadium: "Universitario",
              result: "Empate",
              createdAt: new Date(), 
              updatedAt: new Date()
          },
          {//6to partido
              season: "2020-2021",
              tournament: "clausura",
              journey: 1, 
              date: "09/01",
              time: "21:00 hr", 
              localId: 4, 
              localGol: 2, 
              visitorId: 10, 
              visitorGol: 1, 
              stadium: "Azteca",
              result: "Empate",
              createdAt: new Date(), 
              updatedAt: new Date()
          },
          {//7mo partido
              season: "2020-2021",
              tournament: "clausura",
              journey: 1, 
              date: "10/01",
              time: "12:00 hr", 
              localId: 2, 
              localGol: 3, 
              visitorId: 7, 
              visitorGol: 1, 
              stadium: "Nemesio Diez",
              result: "Empate",
              createdAt: new Date(), 
              updatedAt: new Date()
          },
          {
              season: "2020-2021",
              tournament: "clausura",
              journey: 1, 
              date: "10/01",
              time: "19:06 hr", 
              localId: 6, 
              localGol: 1, 
              visitorId: 5, 
              visitorGol: 0, 
              stadium: "TSM Corona",
              result: "Empate",
              createdAt: new Date(), 
              updatedAt: new Date()
          },
          {
              season: "2020-2021",
              tournament: "clausura",
              journey: 1, 
              date: "11/01",
              time: "21:00 hr", 
              localId: 17, 
              localGol: 1, 
              visitorId: 14,
              visitorGol: 1, 
              stadium: "Hidalgo",
              result: "Empate",
              createdAt: new Date(), 
              updatedAt: new Date()
          },
      
      //========================= season 2 =======================================
      
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 2, 
        date: "15/01", 
        time: "19:30 hr", 
        localId:15, 
        localGol: 1, 
        visitorId:10, 
        visitorGol: 0, 
        stadium: "Victoria",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 2, 
        date: "15/01", 
        time: "21:30 hr", 
        localId:14, 
        localGol: 0, 
        visitorId:1, 
        visitorGol: 0, 
        stadium: "Olímpico Benito Juárez",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 2, 
        date: "16/01", 
        time: "17:00 hr", 
        localId:13, 
        localGol: 1, 
        visitorId:2, 
        visitorGol: 1, 
        stadium: "Estadio AKRON",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 2, 
        date: "16/01", 
        time: "19:00 hr", 
        localId:5, 
        localGol: 0, 
        visitorId:8, 
        visitorGol: 1, 
        stadium: "Azteca",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 2, 
        date: "16/01", 
        time: "21:06 hr", 
        localId:3, 
        localGol: 1, 
        visitorId:4, 
        visitorGol: 0, 
        stadium: "Estadio BBVA",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 2, 
        date: "17/01", 
        time: "12:00 hr", 
        localId:12, 
        localGol: 3,
        visitorId:11, 
        visitorGol: 0, 
        stadium: "Olímpico Universitario",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 2, 
        date: "17/01", 
        time: "19:06 hr", 
        localId:6, 
        localGol: 2, 
        visitorId:9, 
        visitorGol: 0, 
        stadium: "TSM Corona",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 2, 
        date: "17/01", 
        time: "21:06 hr", 
        localId:7, 
        localGol: 1, 
        visitorId:18, 
        visitorGol: 0, 
        stadium: "La Corregidora",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 2, 
        date: "18/01", 
        time: "21:00 hr", 
        localId:16, 
        localGol: 0, 
        visitorId:17, 
        visitorGol: 0, 
        stadium: "Nou Camp",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      
      //============================ jornada 3 =====================================
      
      { 
        season: "2020-2021",
        tournament: "clausura",  
        journey: 3,
        date: "21/01",
        time: "21:00 hr",
        localId: 10,
        localGol: 3,
        visitorId: 13,
        visitorGol: 1,
        stadium: "Alfonso Lastras Ramírez",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      { 
        season: "2020-2021",
        tournament: "clausura",  
        journey: 3,
        date: "22/01",
        time: "19:30 hr",
        localId: 8,
        localGol: 0,
        visitorId: 1,
        visitorGol: 1,
        stadium: "Cuauhtémoc",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      { 
        season: "2020-2021",
        tournament: "clausura",  
        journey: 3,
        date: "22/01",
        time: "21:30 hr",
        localId: 11,
        localGol: 0,
        visitorId: 6,
        visitorGol: 0,
        stadium: "Estadio Mazatlán",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      { 
        season: "2020-2021",
        tournament: "clausura",  
        journey: 3,
        date: "23/01",
        time: "19:00 hr",
        localId: 18,
        localGol: 0,
        visitorId: 9,
        visitorGol: 2,
        stadium: "Jalisco",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      { 
        season: "2020-2021",
        tournament: "clausura",  
        journey: 3,
        date: "24/01",
        time: "12:00 hr",
        localId: 2,
        localGol: 2,
        visitorId: 15,
        visitorGol: 0,
        stadium: "Nemesio Diez",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      { 
        season: "2020-2021",
        tournament: "clausura",  
        journey: 3,
        date: "24/01",
        time: "19:00 hr",
        localId: 7,
        localGol: 2,
        visitorId: 12,
        visitorGol: 0,
        stadium: "La Corregidora",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      { 
        season: "2020-2021",
        tournament: "clausura",  
        journey: 3,
        date: "25/01",
        time: "21:00 hr",
        localId: 17,
        localGol: 0,
        visitorId: 5,
        visitorGol: 1,
        stadium: "Hidalgo",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      { 
        season: "2020-2021",
        tournament: "clausura",  
        journey: 3,
        date: "26/01",
        time: "20:30 hr",
        localId: 4,
        localGol: 2,
        visitorId: 14,
        visitorGol: 0,
        stadium: "Azteca",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      { 
        season: "2020-2021",
        tournament: "clausura",  
        journey: 3,
        date: "10/03",
        time: "21:00 hr",
        localId: 3,
        localGol: 1,
        visitorId: 16,
        visitorGol: 1,
        stadium: "Estadio BBVA",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      
      //============================ jornada 4 =====================================
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 4,
        date: "28/01",
        time: "21:00 hr",
        localId: 9,
        localGol: 1,
        visitorId: 15,
        visitorGol: 1,
        stadium: "Universitario",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 4,
        date: "29/01",
        time: "21:30 hr",
        localId: 11,
        localGol: 1,
        visitorId: 17,
        visitorGol: 0,
        stadium: "Estadio Mazatlán",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 4,
        date: "30/01",
        time: "19:00 hr",
        localId: 13,
        localGol: 1,
        visitorId: 14,
        visitorGol: 2,
        stadium: "Estadio AKRON",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 4,
        date: "30/01",
        time: "21:00 hr",
        localId: 5,
        localGol: 4,
        visitorId: 7,
        visitorGol: 1,
        stadium: "Azteca",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 4,
        date: "30/01",
        time: "21:06 hr",
        localId: 1,
        localGol: 3,
        visitorId: 2,
        visitorGol: 2,
        stadium: "Caliente",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 4,
        date: "31/01",
        time: "12:00 hr",
        localId: 12,
        localGol: 0,
        visitorId: 18,
        visitorGol: 0,
        stadium: "Olímpico Universitario",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 4,
        date: "31/01",
        time: "19:06 hr",
        localId: 6,
        localGol: 1,
        visitorId: 4,
        visitorGol: 1,
        stadium: "TSM Corona",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 4,
        date: "01/02",
        time: "21:00 hr",
        localId: 16,
        localGol: 3,
        visitorId: 10,
        visitorGol: 1,
        stadium: "Nou Camp",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 4,
        date: "02/02",
        time: "21:00 hr",
        localId: 8,
        localGol: 0,
        visitorId: 3,
        visitorGol: 0,
        stadium: "Cuauhtémoc",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      //============================ jornada 5 =====================================
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 5,
        date: "04/02",
        time: "19:00 hr",
        localId: 10,
        localGol: 2,
        visitorId: 1,
        visitorGol: 2,
        stadium: "Alfonso Lastras Ramírez",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
          {
        season: "2020-2021",
        tournament: "clausura",
        journey: 5,
        date: "04/02",
        time: "21:00 hr",
        localId: 7,
        localGol: 3,
        visitorId: 17,
        visitorGol: 1,
        stadium: "La Corregidora",
            result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 5,
        date: "05/02",
        time: "21:30 hr",
        localId: 15,
        localGol: 0,
        visitorId: 5,
        visitorGol: 2,
        stadium: "Victoria",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 5,
        date: "06/02",
        time: "17:00 hr",
        localId: 18,
        localGol: 1,
        visitorId: 6,
        visitorGol: 1,
        stadium: "Jalisco",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 5,
        date: "06/02",
        time: "19:00 hr",
        localId: 4,
        localGol: 1,
        visitorId: 8,
        visitorGol: 0,
        stadium: "Azteca",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 5,
        date: "06/02",
        time: "21:06 hr",
        localId: 3,
        localGol: 1,
        visitorId: 12,
        visitorGol: 0,
        stadium: "Estadio BBVA",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 5,
        date: "07/02",
        time: "12:00 hr",
        localId: 2,
        localGol: 4,
        visitorId: 11,
        visitorGol: 1,
        stadium: "Nemesio Diez",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 5,
        date: "08/02",
        time: "21:00 hr",
        localId: 16,
        localGol: 1,
        visitorId: 13,
        visitorGol: 3,
        stadium: "Nou Camp",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 5,
        date: "14/04",
        time: "21:00 hr",
        localId: 14,
        localGol: 0,
        visitorId: 9,
        visitorGol: 0,
        stadium: "Olímpico Benito Juárez",
        result: "",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      //============================ jornada 6 =====================================
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 6,
        date: "12/02",
        time: "19:30 hr",
        localId: 8,
        localGol: 4,
        visitorId: 14,
        visitorGol: 0,
        stadium: "Cuauhtémoc",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
       {
        season: "2020-2021",
        tournament: "clausura",
        journey: 6,
        date: "12/02",
        time: "21:06 hr",
        localId: 1,
        localGol: 2,
        visitorId: 16,
        visitorGol: 0,
        stadium: "Caliente",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 6,
        date: "12/02",
        time: "21:30 hr",
        localId: 11,
        localGol: 0,
        visitorId: 10,
        visitorGol: 3,
        stadium: "Estadio Mazatlán",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 6,
        date: "13/02",
        time: "19:00 hr",
        localId: 13,
        localGol: 2,
        visitorId: 15,
        visitorGol: 2,
        stadium: "Estadio AKRON",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 6,
        date: "13/02",
        time: "21:00 hr",
        localId: 4,
        localGol: 2,
        visitorId: 7,
        visitorGol: 1,
        stadium: "Azteca",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 6,
        date: "14/02",
        time: "12:00 hr",
        localId: 2,
        localGol: 1,
        visitorId: 12,
        visitorGol: 0,
        stadium: "Nemesio Diez",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 6,
        date: "14/02",
        time: "19:06 hr",
        localId: 6,
        localGol: 1,
        visitorId: 3,
        visitorGol: 0,
        stadium: "TSM Corona",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 6,
        date: "15/02",
        time: "21:00 hr",
        localId: 17,
        localGol: 0,
        visitorId: 18,
        visitorGol: 1,
        stadium: "Hidalgo",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 6,
        date: "17/02",
        time: "21:00 hr",
        localId: 9,
        localGol: 0,
        visitorId: 5,
        visitorGol: 2,
        stadium: "Universitario",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      //============================ jornada 7 =====================================
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 7,
        date: "18/02",
        time: "21:00 hr",
        localId: 10,
        localGol: 1,
        visitorId: 6,
        visitorGol: 0,
        stadium: "Alfonso Lastras Ramírez",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 7,
        date: "19/02",
        time: "19:30 hr",
        localId: 15,
        localGol: 1,
        visitorId: 3,
        visitorGol: 1,
        stadium: "Victoria",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 7,
        date: "19/02",
        time: "21:30 hr",
        localId: 14,
        localGol: 1,
        visitorId: 11,
        visitorGol: 0,
        stadium: "Olímpico Benito Juárez",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 7,
        date: "20/02",
        time: "19:00 hr",
        localId: 5,
        localGol: 3,
        visitorId: 2,
        visitorGol: 2,
        stadium: "Azteca",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 7,
        date: "20/02",
        time: "21:00 hr",
        localId: 18,
        localGol: 3,
        visitorId: 4,
        visitorGol: 0,
        stadium: "Jalisco",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 7,
        date: "21/02",
        time: "12:00 hr",
        localId: 12,
        localGol: 0,
        visitorId: 16,
        visitorGol: 1,
        stadium: "Olímpico Universitario",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 7,
        date: "21/02",
        time: "17:00 hr",
        localId: 7,
        localGol: 1,
        visitorId: 8,
        visitorGol: 1,
        stadium: "La Corregidora",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 7,
        date: "21/02",
        time: "19:00 hr",
        localId: 9,
        localGol: 3,
        visitorId: 1,
        visitorGol: 2,
        stadium: "Universitario",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 7,
        date: "22/02",
        time: "21:00 hr",
        localId: 17,
        localGol: 1,
        visitorId: 13,
        visitorGol: 1,
        stadium: "Hidalgo",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      //============================ jornada 8 =====================================
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 8,
        date: "25/02",
        time: "21:00 hr",
        localId: 10,
        localGol: 2,
        visitorId: 9,
        visitorGol: 2,
        stadium: "Alfonso Lastras Ramírez",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 8,
        date: "26/02",
        time: "19:30 hr",
        localId: 8,
        localGol: 1,
        visitorId: 15,
        visitorGol: 0,
        stadium: "Cuauhtémoc",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 8,
        date: "26/02",
        time: "21:30 hr",
        localId: 11,
        localGol: 3,
        visitorId: 7,
        visitorGol: 0,
        stadium: "Estadio Mazatlán",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 8,
        date: "27/02",
        time: "17:00 hr",
        localId: 2,
        localGol: 0,
        visitorId: 18,
        visitorGol: 0,
        stadium: "Nemesio Diez",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 8,
        date: "27/02",
        time: "19:00 hr",
        localId: 4,
        localGol: 2,
        visitorId: 17,
        visitorGol: 0,
        stadium: "Azteca",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 8,
        date: "27/02",
        time: "21:00 hr",
        localId: 16,
        localGol: 0,
        visitorId: 5,
        visitorGol: 1,
        stadium: "Nou Camp",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 8,
        date: "28/02",
        time: "17:00 hr",
        localId: 3,
        localGol: 1,
        visitorId: 1,
        visitorGol: 1,
        stadium: "Estadio BBVA",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 8,
        date: "28/02",
        time: "19:06 hr",
        localId: 6,
        localGol: 3,
        visitorId: 14,
        visitorGol: 2,
        stadium: "TSM Corona",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 8,
        date: "28/02",
        time: "21:00 hr",
        localId: 13,
        localGol: 2,
        visitorId: 12,
        visitorGol: 1,
        stadium: "Estadio AKRON",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      //============================ jornada 9 =====================================
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 9,
        date: "02/03",
        time: "17:00 hr",
        localId: 18,
        localGol: 3,
        visitorId: 10,
        visitorGol: 1,
        stadium: "Jalisco",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 9,
        date: "02/03",
        time: "19:00 hr",
        localId: 9,
        localGol: 0,
        visitorId: 2,
        visitorGol: 1,
        stadium: "Universitario",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 9,
        date: "02/03",
        time: "21:00 hr",
        localId: 16,
        localGol: 1,
        visitorId: 8,
        visitorGol: 2,
        stadium: "Nou Camp",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 9,
        date: "03/03",
        time: "19:00 hr",
        localId: 7,
        localGol: 2,
        visitorId: 13,
        visitorGol: 2,
        stadium: "La Corregidora",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 9,
        date: "03/03",
        time: "19:00 hr",
        localId: 14,
        localGol: 1,
        visitorId: 3,
        visitorGol: 6,
        stadium: "Olímpico Benito Juárez",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 9,
        date: "03/03",
        time: "21:00 hr",
        localId: 5,
        localGol: 1,
        visitorId: 11,
        visitorGol: 0,
        stadium: "Azteca",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 9,
        date: "03/03",
        time: "21:06 hr",
        localId: 1,
        localGol: 0,
        visitorId: 4,
        visitorGol: 2,
        stadium: "Caliente",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 9,
        date: "04/03",
        time: "19:00 hr",
        localId: 15,
        localGol: 2,
        visitorId: 17,
        visitorGol: 2,
        stadium: "Victoria",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 9,
        date: "04/03",
        time: "21:00 hr",
        localId: 12,
        localGol: 1,
        visitorId: 6,
        visitorGol: 0,
        stadium: "Olímpico Universitario",
        result: "Empate",
        createdAt: new Date(), 
        updatedAt: new Date()
      },
      //============================ jornada 10 =====================================
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 10,
        date: "05/03",
        time: "19:30 hr",
        localId: 10,
        localGol: 0,
        visitorId: 2,
        visitorGol: 0,
        stadium: "Alfonso Lastras Ramírez",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 10,
        date: "05/03",
        time: "21:30 hr",
        localId: 8,
        localGol: 1,
        visitorId: 9,
        visitorGol: 1,
        stadium: "Cuauhtémoc",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 10,
        date: "06/03",
        time: "17:00 hr",
        localId: 18,
        localGol: 2,
        visitorId: 14,
        visitorGol: 0,
        stadium: "Jalisco",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 10,
        date: "06/03",
        time: "19:00 hr",
        localId: 4,
        localGol: 2,
        visitorId: 16,
        visitorGol: 1,
        stadium: "Azteca",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 10,
        date: "06/03",
        time: "19:06 hr",
        localId: 3,
        localGol: 2,
        visitorId: 7,
        visitorGol: 1,
        stadium: "Estadio BBVA",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 10,
        date: "06/03",
        time: "21:00 hr",
        localId: 11,
        localGol: 1,
        visitorId: 13,
        visitorGol: 1,
        stadium: "Estadio Mazatlán",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 10,
        date: "07/03",
        time: "19:06 hr",
        localId: 6,
        localGol: 3,
        visitorId: 15,
        visitorGol: 1,
        stadium: "TSM Corona",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 10,
        date: "07/03",
        time: "21:00 hr",
        localId: 12,
        localGol: 0,
        visitorId: 5,
        visitorGol: 1,
        stadium: "Olímpico Universitario",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 10,
        date: "08/03",
        time: "21:00 hr",
        localId: 17,
        localGol: 2,
        visitorId: 1,
        visitorGol: 1,
        stadium: "Hidalgo",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      //============================ jornada 11 =====================================
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 11,
        date: "12/03",
        time: "19:30 hr",
        localId: 8,
        localGol: 0,
        visitorId: 18,
        visitorGol: 1,
        stadium: "Cuauhtémoc",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 11,
        date: "12/03",
        time: "21:30 hr",
        localId: 14,
        localGol: 1,
        visitorId: 12,
        visitorGol: 1,
        stadium: "Olímpico Benito Juárez",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 11,
        date: "13/03",
        time: "19:00 hr",
        localId: 9,
        localGol: 1,
        visitorId: 11,
        visitorGol: 2,
        stadium: "Universitario",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 11,
        date: "13/03",
        time: "21:00 hr",
        localId: 5,
        localGol: 1,
        visitorId: 3,
        visitorGol: 0,
        stadium: "Azteca",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 11,
        date: "13/03",
        time: "21:06 hr",
        localId: 1,
        localGol: 0,
        visitorId: 6,
        visitorGol: 1,
        stadium: "Caliente",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 11,
        date: "14/03",
        time: "12:00 hr",
        localId: 2,
        localGol: 0,
        visitorId: 17,
        visitorGol: 2,
        stadium: "Nemesio Diez",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 11,
        date: "14/03",
        time: "18:00 hr",
        localId: 7,
        localGol: 2,
        visitorId: 10,
        visitorGol: 1,
        stadium: "La Corregidora",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 11,
        date: "14/03",
        time: "20:00 hr",
        localId: 13,
        localGol: 0,
        visitorId: 4,
        visitorGol: 3,
        stadium: "Estadio AKRON",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 11,
        date: "15/03",
        time: "21:00 hr",
        localId: 16,
        localGol: 3,
        visitorId: 15,
        visitorGol: 1,
        stadium: "Nou Camp",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      //============================ jornada 12 =====================================
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 12,
        date: "18/03",
        time: "20:00 hr",
        localId: 17,
        localGol: 1,
        visitorId: 9,
        visitorGol: 0,
        stadium: "Hidalgo",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 12,
        date: "19/03",
        time: "19:00 hr",
        localId: 15,
        localGol: 1,
        visitorId: 14,
        visitorGol: 0,
        stadium: "Victoria",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 12,
        date: "19/03",
        time: "21:00 hr",
        localId: 11,
        localGol: 0,
        visitorId: 4,
        visitorGol: 1,
        stadium: "Estadio Mazatlán",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 12,
        date: "20/03",
        time: "17:00 hr",
        localId: 10,
        localGol: 0,
        visitorId: 12,
        visitorGol: 1,
        stadium: "Alfonso Lastras Ramírez",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 12,
        date: "20/03",
        time: "19:00 hr",
        localId: 5,
        localGol: 3,
        visitorId: 18,
        visitorGol: 2,
        stadium: "Azteca",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 12,
        date: "20/03",
        time: "21:06 hr",
        localId: 1,
        localGol: 3,
        visitorId: 7,
        visitorGol: 1,
        stadium: "Caliente",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 12,
        date: "21/03",
        time: "12:00 hr",
        localId: 2,
        localGol: 4,
        visitorId: 8,
        visitorGol: 4,
        stadium: "Nemesio Diez",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 12,
        date: "21/03",
        time: "19:06 hr",
        localId: 6,
        localGol: 1,
        visitorId: 16,
        visitorGol: 2,
        stadium: "TSM Corona",
        result: "Empate",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 12,
        date:"21/04",
        time:"21:00 hr",
        localId:3,
        localGol: 0,
        visitorId:13,
        visitorGol: 0,
        stadium: "Estadio BBVA",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      
      //================================== season 13 ==================================
      
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 13,
        date: "02/04",
        time: "19:30 hr",
        localId: 8,
        localGol: 0,
        visitorId: 11,
        visitorGol: 0,
        stadium: "Cuauhtémoc",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 13,
        date: "02/04",
        time: "21:30 hr",
        localId: 14,
        localGol: 0,
        visitorId: 5,
        visitorGol: 0,
        stadium: "Olímpico Benito Juárez",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 13,
        date: "03/04",
        time: "17:00 hr",
        localId: 18,
        localGol: 0,
        visitorId: 1,
        visitorGol: 0,
        stadium: "Jalisco",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 13,
        date: "03/04",
        time: "19:00 hr",
        localId: 4,
        localGol: 0,
        visitorId: 15,
        visitorGol: 0,
        stadium: "Azteca",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 13,
        date: "03/04",
        time: "21:06 hr",
        localId: 3,
        localGol: 0,
        visitorId: 10,
        visitorGol: 0,
        stadium: "Estadio BBVA",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 13,
        date: "04/04",
        time: "12:00 hr",
        localId: 12,
        localGol: 0,
        visitorId: 17,
        visitorGol: 0,
        stadium: "Olímpico Universitario",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 13,
        date: "04/04",
        time: "17:00 hr",
        localId: 13,
        localGol: 0,
        visitorId: 6,
        visitorGol: 0,
        stadium: "Estadio AKRON",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 13,
        date: "04/04",
        time: "19:00 hr",
        localId: 7,
        localGol: 0,
        visitorId: 9,
        visitorGol: 0,
        stadium: "La Corregidora",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 13,
        date: "04/04",
        time: "21:05 hr",
        localId: 16,
        localGol: 0,
        visitorId: 2,
        visitorGol: 0,
        stadium: "Nou Camp",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
       //================================== season 14 ==================================
       
       
      {
        season: "2020-2021",
        tournament: "clausura",
        journey:14,
        date: "09/04",
        time: "19:30 hr",
        localId: 15,
        localGol: 0,
        visitorId: 12,
        visitorGol: 0,
        stadium: "Victoria",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",  
        journey: 14,
        date: "09/04",
        time: "21:30 hr",
        localId: 14,
        localGol: 0,
        visitorId: 10,
        visitorGol: 0,
        stadium: "Olímpico Benito Juárez",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
        },
        {
          season: "2020-2021",
          tournament: "clausura",
          journey: 14,
          date: "10/04",
          time: "17:00 hr",
          localId: 18,
          localGol: 0,
          visitorId: 16,
          visitorGol: 0,
          stadium: "Jalisco",
          result: "por jugar",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          season: "2020-2021",
          tournament: "clausura",
          journey: 14,
          date: "10/04",
          time: "19:00 hr",
          localId: 5,
          localGol: 0,
          visitorId: 13,
          visitorGol: 0,
          stadium: "Azteca",
          result: "por jugar",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          season: "2020-2021",
          tournament: "clausura",
          journey: 14,
          date: "10/04",
          time: "21:05 hr",
          localId: 9,
          localGol: 0,
          visitorId: 4,
          visitorGol: 0,
          stadium: "Universitario",
          result: "por jugar",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          season: "2020-2021",
          tournament: "clausura",
          journey: 14,
          date: "11/04",
          time: "12:00 hr",
          localId: 2,
          localGol: 0,
          visitorId: 3,
          visitorGol: 0,
          stadium: "Nemesio Diez",   
          result: "por jugar",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          season: "2020-2021",
          tournament: "clausura",
          journey: 14,
          date: "11/04",
          time: "19:00 hr",
          localId: 7,
          localGol: 0,
          visitorId: 6,
          visitorGol: 0,
          stadium: "La Corregidora",   
          result: "por jugar",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          season: "2020-2021",
          tournament: "clausura",
          journey: 14,
          date: "11/04",
          time: "21:06 hr",
          localId: 1,
          localGol: 0,
          visitorId: 11,
          visitorGol: 0,
          stadium: "Caliente",   
          result: "por jugar",
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          season: "2020-2021",
          tournament: "clausura",
          journey: 14,
          date: "12/04",
          time: "21:00 hr",
          localId: 17,
          localGol: 0,
          visitorId: 8,
          visitorGol: 0,
          stadium: "Hidalgo",   
          result: "por jugar",
          createdAt: new Date(),
          updatedAt: new Date()
        },
      //================================== season 15 ==================================
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 15,
        date: "16/04",
        time: "19:30 hr",
        localId: 15,
        localGol:0,
        visitorId: 7,
        visitorGol: 0,
        stadium: "Victoria",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 15,
        date: "16/04",
        time: "21:30 hr",
        localId: 11,
        localGol:0,
        visitorId: 18,
        visitorGol: 0,
        stadium: "Estadio Mazatlán",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 15,
        date: "17/04",
        time: "17:00 hr",
        localId: 10,
        localGol:0,
        visitorId: 8,
        visitorGol: 0,
        stadium: "Alfonso Lastras Ramírez",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 15,
        date: "17/04",
        time: "19:00 hr",
        localId: 13,
        localGol:0,
        visitorId: 1,
        visitorGol: 0,
        stadium: "Estadio AKRON",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 15,
        date: "17/04",
        time: "21:05 hr",
        localId: 4,
        localGol:0,
        visitorId: 5,
        visitorGol: 0,
        stadium: "Azteca",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 15,
        date: "18/04",
        time: "12:00 hr",
        localId: 12,
        localGol:0,
        visitorId: 9,
        visitorGol: 0,
        stadium: "Olímpico Universitario",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 15,
        date: "18/04",
        time: "19:00 hr",
        localId: 6,
        localGol:0,
        visitorId: 2,
        visitorGol: 0,
        stadium: "TSM Corona",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 15,
        date: "18/04",
        time: "21:06 hr",
        localId: 3,
        localGol:0,
        visitorId: 17,
        visitorGol: 0,
        stadium: "Estadio BBVA",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 15,
        date: "19/04",
        time: "21:00 hr",
        localId: 16,
        localGol:0,
        visitorId: 14,
        visitorGol: 0,
        stadium: "Nou Camp",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      },
        //================================== season 16 ==================================
      
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 16,
        date: "23/04",
        time: "19:30 hr",
        localId: 8,
        localGol: 0,
        visitorId: 12,
        visitorGol: 0,
        stadium: "Cuauhtémoc",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 16,
        date: "23/04",
        time: "21:06 hr",
        localId: 1,
        localGol: 0,
        visitorId: 15,
        visitorGol: 0,
        stadium: "Caliente",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 16,
        date: "23/04",
        time: "21:30 hr",
        localId: 11,
        localGol: 0,
        visitorId: 16,
        visitorGol: 0,
        stadium: "Estadio Mazatlán",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 16,
        date: "24/04",
        time: "17:00 hr",
        localId: 5,
        localGol: 0,
        visitorId: 10,
        visitorGol: 0,
        stadium: "Azteca",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 16,
        date: "24/04",
        time: "19:00 hr",
        localId: 18,
        localGol: 0,
        visitorId: 13,
        visitorGol: 0,
        stadium: "Jalisco",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 16,
        date: "24/04",
        time: "21:00 hr",
        localId: 9,
        localGol: 0,
        visitorId: 3,
        visitorGol: 0,
        stadium: "Universitario",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 16,
        date: "25/04",
        time: "17:30 hr",
        localId: 2,
        localGol: 0,
        visitorId: 4,
        visitorGol: 0,
        stadium: "Nemesio Diez",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 16,
        date: "25/04",
        time: "19:30 hr",
        localId: 7,
        localGol: 0,
        visitorId: 14,
        visitorGol: 0,
        stadium: "La Corregidora",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 16,
        date: "26/04",
        time: "21:00 hr",
        localId: 17,
        localGol: 0,
        visitorId: 6,
        visitorGol: 0,
        stadium: "Hidalgo",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
        //================================== season 17 ==================================
      
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 17,
        date: "29/04",
        time: "21:00 hr",
        localId: 10,
        localGol: 0,
        visitorId: 17,
        visitorGol: 0,
        stadium: "Alfonso Lastras Ramírez",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 17,
        date: "30/04",
        time: "19:30 hr",
        localId: 15,
        localGol: 0,
        visitorId: 18,
        visitorGol: 0,
        stadium: "Victoria",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 17,
        date: "30/04",
        time: "21:30 hr",
        localId: 14,
        localGol: 0,
        visitorId: 2,
        visitorGol: 0,
        stadium: "Olímpico Benito Juárez",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 17,
        date: "01/05",
        time: "17:00 hr",
        localId: 13,
        localGol: 0,
        visitorId: 9,
        visitorGol: 0,
        stadium: "Estadio AKRON",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 17,
        date: "01/05",
        time: "17:00 hr",
        localId: 16,
        localGol: 0,
        visitorId: 7,
        visitorGol: 0,
        stadium: "Nou Camp",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 17,
        date: "01/05",
        time: "19:00 hr",
        localId: 5,
        localGol: 0,
        visitorId: 1,
        visitorGol: 0,
        stadium: "Azteca",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 17,
        date: "01/05",
        time: "21:06 hr",
        localId: 3,
        localGol: 0,
        visitorId: 11,
        visitorGol: 0,
        stadium: "Estadio BBVA",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 17,
        date: "02/05",
        time: "19:06 hr",
        localId: 6,
        localGol: 0,
        visitorId: 8,
        visitorGol: 0,
        stadium: "TSM Corona",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
        
      {
        season: "2020-2021",
        tournament: "clausura",
        journey: 17,
        date: "02/05",
        time: "21:00 hr",
        localId: 12,
        localGol: 0,
        visitorId: 4,
        visitorGol: 0,
        stadium: "Olímpico Universitario",
        result: "por jugar",
        createdAt: new Date(),
        updatedAt: new Date()
      }, 
             
      ], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('games', null, {});
  }
};
